Repository tp0ns/ft_transcendence, pull requests merged in 2022-08, with the labels that each got.

#36 Auth frontend
  backend/src/auth/2FA/dto/token.interface.ts
  backend/src/auth/2FA/twoFA.controller.ts
  backend/src/auth/2FA/twoFA.service.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.strategy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/Globals.d.ts
  frontend/src/Pages/LoginPage.tsx
  frontend/src/Pages/TwoFAPage.tsx
  frontend/src/components/RequireAuth.tsx
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/main.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: new feature

#37 Navbar frontend
  docker-compose.yml
  frontend/public/chat.svg
  frontend/public/favicon.ico
  frontend/public/fonts/blippo_black_font/blippo_black_regular-demo.html
  frontend/public/fonts/blippo_black_font/blippo_black_regular-webfont.woff
  frontend/public/fonts/blippo_black_font/blippo_black_regular-webfont.woff2
  frontend/public/fonts/blippo_black_font/generator_config.txt
  frontend/public/fonts/blippo_black_font/specimen_files/grid_12-825-55-15.css
  frontend/public/fonts/blippo_black_font/specimen_files/specimen_stylesheet.css
  frontend/public/fonts/blippo_black_font/stylesheet.css
  frontend/public/friends.svg
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/pong.svg
  frontend/public/user.svg
  frontend/src/App.tsx
  frontend/src/Pages/ChatPage.tsx
  frontend/src/Pages/GamePage.tsx
  frontend/src/Pages/SocialPage.tsx
  frontend/src/Pages/TwoFAPage.tsx
  frontend/src/Pages/UserPage.tsx
  frontend/src/components/Auth.tsx
  frontend/src/components/NavBar/NavBar.module.css
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/index.css
Labels: new feature

#38 delete channel and dependencies and settings (ban, mute, invitations, new admin) working
  backend/.eslintrc.js
  backend/.prettierrc
  backend/src/app.controller.ts
  backend/src/chat/channel/channel.entity.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/channel/dtos/modifyChan.dto.ts
  backend/src/game/game.ts
  backend/src/general.gateway.ts
  frontend/src/App.tsx
  frontend/src/Pages/ChatPage.module.css
  frontend/src/Pages/ChatPage.tsx
  frontend/src/Pages/Debug.tsx
  frontend/src/Pages/GamePage.tsx
  frontend/src/components/ChannelItem.tsx
  frontend/src/components/ChannelsLists.tsx
  frontend/src/components/channel/ChannelItem.tsx
  frontend/src/components/channel/ChannelsLists.tsx
  frontend/src/components/channel/MessagesLists.tsx
  frontend/src/components/channel/NewChannel.tsx
  frontend/src/components/channel/NewChannelForm.module.css
  frontend/src/components/channel/OpenedChannel.tsx
  frontend/src/components/channel/Settings.tsx
  frontend/src/components/game/Game.vue
  frontend/src/components/game/GameScreen.module.css
  frontend/src/components/game/GameScreen.tsx
  frontend/src/index.tsx
  frontend/src/interfaces/Channel.interface.ts
  frontend/src/interfaces/User.interface.tsx
  frontend/src/interfaces/modifyChannelInterface.tsx
  frontend/src/models/channel.ts
  frontend/src/store/channels-context.tsx
  frontend/src/store/socket-context.tsx
  frontend/src/ui/InputAndButton.tsx
Labels: new feature

#40 Auth frontend update
  backend/src/auth/websocket/ws.guard.ts
  frontend/public/42_Logo.png
  frontend/src/App.tsx
  frontend/src/Pages/Login/LoginPage.module.css
  frontend/src/Pages/Login/LoginPage.tsx
  frontend/src/Pages/Login/TwoFAPage.module.css
  frontend/src/Pages/Login/TwoFAPage.tsx
  frontend/src/Pages/LoginPage.tsx
  frontend/src/components/Auth.tsx
Labels: Upgrade

#41 3 chat
  backend/src/app.module.ts
  backend/src/chat/channel/channel.entity.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/messages/messages.entity.ts
  backend/src/user/dtos/user.dto.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
  backend/src/websocket/general.module.ts
  backend/src/websocket/general.service.ts
  frontend/src/App.tsx
  frontend/src/Pages/ChatPage.tsx
Labels: new feature, Upgrade

#46 3 chat
  backend/src/app.module.ts
  backend/src/chat/DM/DM.entity.ts
  backend/src/chat/DM/DM.service.ts
  backend/src/chat/DM/createDM.dto.ts
  backend/src/chat/channel/channel.controller.ts
  backend/src/chat/channel/channel.entity.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/channel/dtos/joinChan.dto.ts
  backend/src/chat/messages/messages.service.ts
  backend/src/user/models/user.entity.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
  backend/src/websocket/general.module.ts
  frontend/src/Pages/ChatPage.module.css
  frontend/src/Pages/ChatPage.tsx
  frontend/src/Pages/SocialPage.tsx
  frontend/src/components/channel/ChannelItem.tsx
  frontend/src/components/channel/ChannelMembersList.tsx
  frontend/src/components/channel/ChannelsLists.tsx
  frontend/src/components/channel/MemberItem.tsx
  frontend/src/components/channel/NewChannel.tsx
  frontend/src/components/channel/NewChannelForm.module.css
  frontend/src/components/channel/OpenedChannel.tsx
  frontend/src/components/channel/Settings.tsx
  frontend/src/interfaces/DM.interface.ts
Labels: bug, new feature, Upgrade
