Repository tp0ns/ft_transcendence, pull requests merged in 2022-09, with the labels that each got.

#83 version finale chat
  backend/src/auth/2FA/twoFA.module.ts
  backend/src/auth/auth.module.ts
  backend/src/chat/channel/channel.controller.ts
  backend/src/chat/channel/channel.entity.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/channel/dtos/createChan.dto.ts
  backend/src/chat/channel/dtos/joinChan.dto.ts
  backend/src/chat/channel/dtos/modifyChan.dto.ts
  backend/src/chat/messages/messages.service.ts
  backend/src/globalException.filter.ts
  backend/src/main.ts
  backend/src/relations/relations.module.ts
  backend/src/relations/relations.service.ts
  backend/src/user/dtos/user.dto.ts
  backend/src/user/user.module.ts
  backend/src/websocket/dtos/Relations.dto.ts
  backend/src/websocket/general.gateway.ts
  backend/tsconfig.build.json
  frontend/public/adduser.svg
  frontend/src/App.tsx
  frontend/src/Pages/ChatPage/ChatPage.tsx
  frontend/src/Pages/SocialPage.tsx
  frontend/src/components/Error/ErrorBadge.module.css
  frontend/src/components/Error/ErrorBadge.tsx
  frontend/src/components/Layout/NavBar/NavBar.tsx
  frontend/src/components/chat/ChanContent/ChanContent.module.css
  frontend/src/components/chat/ChanContent/ChanContent.tsx
  frontend/src/components/chat/ChanContent/ChanMsgs/ChanMsgs.tsx
  frontend/src/components/chat/ChanContent/ChanMsgs/ChanSettings/ChanSettings.module.css
  frontend/src/components/chat/ChanContent/ChanMsgs/ChanSettings/ChanSettings.tsx
  frontend/src/components/chat/ChanContent/ChanMsgs/Message/Message.module.css
  frontend/src/components/chat/ChanContent/ChanMsgs/Message/Message.tsx
  frontend/src/components/chat/ChanContent/ChanProtect/ChanProtect.module.css
  frontend/src/components/chat/ChanContent/ChanProtect/ChanProtect.tsx
  frontend/src/components/chat/ChanContent/MemberList/AdminMemberItem/AdminMemberItem.module.css
  frontend/src/components/chat/ChanContent/MemberList/AdminMemberItem/AdminMemberItem.tsx
  frontend/src/components/chat/ChanContent/MemberList/BannedMemberItem/BannedMemberItem.module.css
  frontend/src/components/chat/ChanContent/MemberList/BannedMemberItem/BannedMemberItem.tsx
  frontend/src/components/chat/ChanContent/MemberList/MemberList.module.css
  frontend/src/components/chat/ChanContent/MemberList/MemberList.tsx
  frontend/src/components/chat/ChanContent/MemberList/NormalMemberItem/NormalMemberItem.module.css
  frontend/src/components/chat/ChanContent/MemberList/NormalMemberItem/NormalMemberItem.tsx
  frontend/src/components/chat/ChanList/Chan/Chan.tsx
  frontend/src/components/chat/ChannelMembersList.tsx
  frontend/src/components/chat/MemberItem.tsx
  frontend/src/components/chat/MemberList/MemberList.module.css
  frontend/src/components/chat/MemberList/MemberList.tsx
  frontend/src/components/chat/MemberList/NormalMemberItem/NormalMemberItem.module.css
  frontend/src/components/chat/MemberList/NormalMemberItem/NormalMemberItem.tsx
  frontend/src/components/chat/Settings.tsx
  frontend/src/components/social/RelationItem.tsx
  frontend/src/components/social/RelationsList.tsx
  frontend/src/context/chat-context.tsx
  frontend/src/context/error-context.tsx
  frontend/src/interfaces/Relations.interface.tsx
  frontend/src/types/ErrorContextType.tsx
  package-lock.json
  package.json
Labels: Upgrade

#93 Final modifications chat clbouche
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/channel/dtos/createChan.dto.ts
  backend/src/websocket/general.gateway.ts
  backend/tsconfig.build.json
Labels: Upgrade

#98 derniere modif du chat : password
  backend/src/chat/channel/channel.entity.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/globalException.filter.ts
  backend/src/websocket/general.module.ts
Labels: Upgrade

#105 DM OK || debut des achievements
  backend/src/auth/websocket/ws.guard.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/game/game.service.ts
  backend/src/game/invitations/invitations.entity.ts
  backend/src/game/statistics/achievements.entity.ts
  backend/src/game/statistics/oneAchievement.entity.ts
  backend/src/user/models/user.entity.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
  backend/src/websocket/general.module.ts
  backend/uploads/profileimages/Invitation_FeÌte_de_l'HumaniteÌ_2022_2022_Bondesoutien_0709100103185652364927-4221-40e5-9262-bb2932af0775.PDF
  backend/uploads/profileimages/Invitation_FeÌte_de_l'HumaniteÌ_2022_2022_Bondesoutien_07091001031856d0ad811b-d1ef-43c7-8daf-d85bb13e8cbe.PDF
  frontend/src/Pages/GamePage.tsx
  frontend/src/components/game/GameScreen.module.css
  frontend/src/components/game/GameScreen.tsx
  frontend/src/components/social/RelationItem.tsx
  frontend/tsconfig.json
Labels: new feature, Upgrade

#106 Achievements and stats for game
  backend/src/auth/2FA/twoFA.module.ts
  backend/src/auth/auth.module.ts
  backend/src/chat/channel/channel.service.ts
  backend/src/game/game.service.ts
  backend/src/game/statistics/achievements.entity.ts
  backend/src/game/statistics/oneAchievement.entity.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
  backend/src/websocket/general.module.ts
Labels: new feature

#112 Userpage tpons update
  backend/src/game/game.service.ts
  backend/src/game/matchHistory/matchHistory.entity.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
Labels: new feature, Upgrade

#116 Clbouche global fix
  backend/src/websocket/general.gateway.ts
  frontend/src/components/social/RelationItem.tsx
Labels: Upgrade

#118 Clbouche global fix
  backend/src/chat/channel/dtos/createChan.dto.ts
  backend/src/chat/messages/messages.entity.ts
  backend/src/chat/messages/messages.service.ts
  backend/src/game/game.service.ts
  backend/src/globalException.filter.ts
  backend/src/main.ts
  backend/src/user/models/user.entity.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
Labels: Upgrade

#129 new game on fire
  backend/src/game/game.service.ts
  backend/src/game/interfaces/game.interface.ts
  backend/src/game/interfaces/match.interface.ts
  backend/src/game/invitations/invitation.interface.ts
  backend/src/game/utils/initGrid.ts
  backend/src/user/models/user.entity.ts
  backend/src/user/user.service.ts
  backend/src/websocket/general.gateway.ts
  frontend/src/App.tsx
  frontend/src/Pages/GamePage.module.css
  frontend/src/Pages/GamePage.tsx
  frontend/src/Pages/HomePage/HomePage.module.css
  frontend/src/Pages/HomePage/HomePage.tsx
  frontend/src/Pages/SocialPage/SocialPage.module.css
  frontend/src/Pages/SocialPage/SocialPage.tsx
  frontend/src/Pages/WaitingPage/WaitingPage.module.css
  frontend/src/Pages/WaitingPage/WaitingPage.tsx
  frontend/src/components/Layout/NavBar/NavBar.tsx
  frontend/src/components/chat/ChanContent/MemberList/AdminMemberItem/AdminMemberItem.tsx
  frontend/src/components/chat/ChanContent/MemberList/NormalMemberItem/NormalMemberItem.tsx
  frontend/src/components/game/Game.vue
  frontend/src/components/game/GameCanvas.css
  frontend/src/components/game/GameCanvas.tsx
  frontend/src/components/game/GameScreen.tsx
  frontend/src/components/game/InviteItem/InviteItem.tsx
  frontend/src/components/game/interfaces/game.interfaces.tsx
  frontend/src/components/game/utils/GameDraw.tsx
  frontend/src/components/social/RelationItem.tsx
  frontend/src/components/social/RelationsList.tsx
  frontend/src/components/user/MatchList/MatchList.tsx
  frontend/src/components/user/UserContent/UserContent.tsx
  frontend/src/context/error-context.tsx
  frontend/src/interfaces/MatchInvite.interface.tsx
Labels: Upgrade

#130 125 refacto invite matchmaking
  backend/src/game/game.service.ts
  backend/src/game/interfaces/game.interface.ts
  backend/src/websocket/general.gateway.ts
  frontend/src/Pages/GamePage.tsx
  frontend/src/components/Auth.tsx
  frontend/src/components/game/interfaces/game.interfaces.tsx
  frontend/src/components/user/StatList/AchievementList.tsx
Labels: Upgrade

#131 Global fix new game
  backend/src/chat/channel/channel.service.ts
  backend/src/chat/messages/messages.service.ts
  backend/src/relations/relations.service.ts
  backend/src/websocket/general.gateway.ts
  frontend/src/Pages/WaitingPage/WaitingPage.tsx
  frontend/src/context/chat-context.tsx
Labels: Upgrade

#132 125 refacto invite matchmaking
  backend/src/game/game.service.ts
  backend/src/game/interfaces/game.interface.ts
  backend/src/game/utils/initGrid.ts
  backend/src/websocket/general.gateway.ts
  frontend/src/Pages/HomePage/HomePage.module.css
  frontend/src/Pages/HomePage/HomePage.tsx
  frontend/src/components/game/GameCanvas.css
  frontend/src/components/game/interfaces/game.interfaces.tsx
Labels: Upgrade

#136 125 refacto invite matchmaking
  backend/src/chat/channel/channel.service.ts
  backend/src/websocket/general.gateway.ts
Labels: Upgrade

#137 125 refacto invite matchmaking
  backend/src/game/game.service.ts
  backend/src/websocket/general.gateway.ts
Labels: Upgrade

#140 125 refacto invite matchmaking
  backend/src/chat/channel/channel.service.ts
  backend/src/game/game.service.ts
  backend/src/websocket/general.gateway.ts
Labels: Upgrade

#141 125 refacto invite matchmaking
  backend/src/game/game.service.ts
  backend/src/game/interfaces/game.interface.ts
  backend/src/websocket/general.gateway.ts
  frontend/src/components/game/interfaces/game.interfaces.tsx
  frontend/src/components/user/MatchList/MatchList.tsx
Labels: Upgrade

#143 125 refacto invite matchmaking
  frontend/src/Pages/GamePage.tsx
Labels: Upgrade

#148 movePad error ok
  Caddyfile
  backend/src/game/game.service.ts
Labels: Upgrade

#150 Final final
  backend/src/globalException.filter.ts
Labels: Upgrade

#151 Final final
  backend/src/auth/websocket/ws.guard.ts
  backend/src/websocket/general.gateway.ts
Labels: Upgrade

#152 Final final
  frontend/src/Pages/GamePage.tsx
Labels: Upgrade
